### ISSUE TITLE
Conversion issues

### ISSUE THREAD

**Issue by ollelogdahl** [aminophen/dviasm#19] opened 2020-11-14 10:47 UTC
Im getting unexpected and incorrect `dvi` codes after converting to and from `dviasm`.

`dvipdf` output:
![run_1](https://user-images.githubusercontent.com/37961475/99145255-820b4700-266d-11eb-90f6-908b780ad3b7.png)
`dvipdf` output, after converting to & from `dviasm`:
![run_2](https://user-images.githubusercontent.com/37961475/99145257-87689180-266d-11eb-96ab-52cb66eb1af0.png)

**Steps to reproduce**:
I have a .dvi file, built with `groff`.
```
> echo ".PP\nabcdefåäö" > min.ms
> groff -Tdvi -k -ms min.ms > min.dvi
```
Now converting it to and from dviasm:
```
> dviasm -o min.dviasm min.dvi
> dviasm -o min_conv.dvi min.dviasm
```
Displaying `min.dvi` with `dvipdf` gives output displayed in pic 1.
Displaying `min_conv.dvi` with `dvipdf` gives output displayed in pic 2.

Also confirmed that there is a difference between `min.dvi` `min_conv.dvi`.

Not sure if i can embedd files in this report. If someone is looking into it, i can send the built dvi from groff. Don't think this is groff related.

**Comment by ollelogdahl** [comment] 2020-11-14 14:21
Upon further analysis, this does not seem to have anything to do with the groff system.
Comparing the `dvi` before and after converting to and from `dviasm` (by printing them both `dvitype`, and only showing the first faulty character) yields:

*before*
```
setchar97 [a]
right2 -4998
setchar23 [???]
right2 -1000
```

*after*
```
setchar97 [a]
right2 -4998
setchar92 [\]
setchar120 [x]
setchar49 [1]
setchar55 [7]
right2 -1000
```

It becomes apparent that there is some escaping going on. `dviasm` converts 'a + ¨' (ä) to 'a + \x17'

**Comment by aminophen** [comment] 2020-11-14 14:42
@ollelogdahl Which version of DVIasm are you using? I cannot reproduce such a problem; may be you are running an older release? (see #12.)

**Comment by aminophen** [comment] 2022-03-10 14:28
I'll close this since I cannot reproduce.

**Closed as completed by aminophen** 2022-03-10 14:28 UTC
